
import = [
    "~/bin/alacritty/themes/memories.toml"
]

[window]
opacity = 1.0
decorations = "None"
startup_mode = "Fullscreen"
dynamic_padding = true

[font]
size = 18.0

[cursor]
style = "Block"
unfocused_hollow = true

[terminal]
osc52 = "OnlyCopy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
